config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => "registrations" }
  devise_scope :user do
    get '/trip_preview/join/:id', :as=> 'trip_preview_join', :to => 'registrations#new'
  end
  
  get 'info_map/index'

  root to: 'visitors#index'
 
  authenticated :user do
    root 'user#show', as: :authenticated_root
  end

  resources :users, except: :index
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :trip, except: [:index, :edit] do
  	resources :trip_route, only: [:show]
    resources :comments, only: [:create]
    resources :itineraries, only:[:show]
  end
  
  resources :trip_preview, only: [:show]
  match '/trip_route/update', to: 'trip_route#update', via: [:post], constraints: { format: 'json' }
  match '/trip_route/stop/delete', to: 'trip_route#edit', via: [:post], constraints: { format: 'json' }
  match '/trip/:id', to: 'trip#update', via: [:patch], constraints: { format: 'json' }
  resources :comments
  resources :info_map, only: [:index]

  resource :budgets
  post '/budgets/compute' => 'budgets#compute'

end
 

app/controllers/trip_preview_controller.rb
class TripPreviewController < ApplicationController

	def show
		@trip = Trip.find_by(trip_code:params[:id])
	end	

end

app/helpers/trip_preview_helper.rb
module TripPreviewHelper
end

app/views/trip_preview/show.html.erb
<h1><%= @trip.name %></h1>
<p>You've been invited to join <%= @trip.users[0].name%>'s trip!</p>
<p>Here's what they've got so far!</p>

<%= @trip.users[0].name%> is planning to visit <%= @trip.itinerary.area %> for <%= @trip.itinerary.cities.length %> days!

<% if @trip.itinerary_id %>
		<h2>This is the sample itinerary they are thinking to follow!</h2>
		<ol>	
			<% @trip.itinerary.cities.each do |stop| %>
			<li> <%= stop %> </li>
			<% end %>
		</ol>
		<h2>Stops</h2>
		<ol>
			<% @trip.itinerary.countries.each do |country| %>
			<li> <%= country %></li>
			<% end %>
		</ol>
<% end %>

Approx Budget

<%= link_to "Join Backpackers Now!", trip_preview_join_path(@trip.trip_code) %>