config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => "registrations" }
  devise_scope :user do
    get '/trip_preview/join/:id', :as=> 'trip_preview_join', :to => 'registrations#new'
  end
  
  get 'info_map/index'

  root to: 'visitors#index'
 
  authenticated :user do
    root 'user#show', as: :authenticated_root
  end

  resources :users, except: :index
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :trip, except: [:index, :edit] do
  	resources :trip_route, only: [:show]
    resources :comments, only: [:create]
    resources :itineraries, only:[:show]
  end
  
  resources :trip_preview, only: [:show]
  match '/trip_route/update', to: 'trip_route#update', via: [:post], constraints: { format: 'json' }
  match '/trip_route/stop/delete', to: 'trip_route#edit', via: [:post], constraints: { format: 'json' }
  match '/trip/:id', to: 'trip#update', via: [:patch], constraints: { format: 'json' }
  resources :comments
  resources :info_map, only: [:index]

  resource :budgets
  post '/budgets/compute' => 'budgets#compute'

end
 

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

  def show
    @countries = Country.all
    @expenses = CountryExpense.all
  end

  def compute

    option = params[:option].to_i

    if option == 1
      my_country_id = params[:country].to_i
      my_budget = params[:budget].to_i
      
      country_name = Calculator.get_country_name_by_id(my_country_id)
      result = Calculator.calculate_expected_trip_days(my_budget,country_name)
      my_data = Calculator.country_info(country_name)
      percent = my_data[6]

      all = Calculator.get_all_info_from_country(my_country_id)
      canada_currency = Calculator.convert_currency(my_data[2])

      fun_info = []

      all.each do |item|
        converted_money = (item.total/canada_currency).round(2)
        fun_info.push([item.expense_type, converted_money])
      end

      render json: { country_name: country_name.to_json, percent: percent.to_json, result: result.to_json, fun_info: fun_info.to_json }


    elsif option == 2
      my_country_id = params[:country].to_i
      my_days = params[:days].to_i

      country_name = Calculator.get_country_name_by_id(my_country_id)
      result = Calculator.calculate_expected_budget(my_days, country_name)
      my_data = Calculator.country_info(country_name)
      percent = Calculator.country_info(country_name)[6]

      all = Calculator.get_all_info_from_country(my_country_id)
      canada_currency = Calculator.convert_currency(my_data[2])

      fun_info = []

      all.each do |item|
        converted_money = (item.total/canada_currency).round(2)
        fun_info.push([item.expense_type, converted_money])
      end

      render json: { country_name: country_name.to_json, percent: percent.to_json, result: result.to_json, fun_info: fun_info.to_json }

    # elsif option == 3
    #   my_budget = params[:budget].to_i
    #   my_days = params[:days].to_i

    #   result = Calculator.show_country_suggestion(my_days, my_budget)

    #   render json: { result: result.to_json }
    end

  end

end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/show.html.erb
<!-- getting country data from DB -->
<% country_array = @countries.map { |c| [c.country, c.id] } %>


<!-- for option 1 -->
<div>
  <div class="preview-wrapper">

    <div class="space"><br /></div>

    <section>
    <div class="transbox">
      <div class="row">
        <div class="small-12 large-8 columns large-centered">
          <h1 class="option">Option 1: Country and Budget</h1>

          <%= form_tag(budgets_compute_path, method: :post, id: 'budgets_form1') do %>

            <%= hidden_field_tag :option, 1 %>
            <div class="row">
              <div class="large-6 small-12 columns">
                <%= label_tag :country %>
                <%= select_tag "country", options_for_select(country_array, "Select Country") %>
              </div>
              <div class="large-6 small-12 columns">
                <%= label_tag :budget, "Budget in CAD" %>
                <%= number_field_tag :budget %>
              </div>
            </div>
            <br />
            <%= submit_tag("Submit", :class => "button", :id => "output1") %>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="large-12 columns">
          <div id="outputbox1">

          </div>
        </div>
      </div>


      <div class="row">
        <div class="large-1 columns"><br /></div>
          <div class="large-4 columns" id="mypie1">

          </div>

          <div class="large-6 end columns">
            <table id="myFunTable1" style="display:none;">
              <thead>
                <th>Type of Expenses</th>
                <th>Daily Cost in CAD</th>
              </thead>
              <tbody>

              </tbody>
            </table>
          </div>
        </div>
        <br /><br />

      </div>
    </section>


    <!-- for option 2 -->

    <section">

      <div class="transbox">
        <div class="row">
          <div class="small-12 large-8 columns small-centered large-centered">
            <h1 class="option">Option 2: Country and Days</h1>

            <%= form_tag(budgets_compute_path, method: :post, id: 'budgets_form2') do %>

              <%= hidden_field_tag :option, 2 %>
              <div class="row">
                <div class="large-6 small-12 columns">
                  <%= label_tag :country %>
                  <%= select_tag "country", options_for_select(country_array, "Select Country") %>
                </div>
                <div class="large-6 small-12 columns">
                  <%= label_tag :days, "Days" %>
                  <%= number_field_tag :days %>
                </div>
              </div>
              <br />
              <%= submit_tag("Submit", :class => "button", :id => "output2") %>
            <% end %>
          </div>
          <br /><br />
        </div>
      <div class="row">
        <div class="large-12 columns">
          <div id="outputbox2">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="large-1 columns"><br /></div>
          <div class="large-4 columns" id="mypie2">
          </div>
          <div class="large-6 end columns">
            <table id="myFunTable2" style="display: none;">
              <thead>
                <th>Type of Expenses</th>
                <th>Daily Cost in CAD</th>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>
        <br /><br />
      </div>
    </section>
  </div>
</div>
<!-- for option 3 -->

<!-- <section class="search">
  <div class="row">
    <div class="small-12 large-8 columns large-centered small-centered">
      <hr /><br /><br />
      <h1>Option 3: Budget and Days</h1>
      <br /><br />

      <%= form_tag(budgets_compute_path, method: :post, id: 'budgets_form3') do %>

        <%= hidden_field_tag :option, 3 %>
        <div class="row">

          <div class="large-6 small-12 columns">
            <%= label_tag :budget, "Budget in CAD" %>
            <%= number_field_tag :budget %>
          </div>
          <div class="large-6 small-12 columns">
            <%= label_tag :days, "Days" %>
            <%= number_field_tag :days %>
          </div>
        </div>
        <div class="row">
          <%= submit_tag("Submit", :class => "button large-6 small-12 columns large-centered", :id => "output3") %>
        </div>
      <% end %>

    </div>
    <br /><br />
  </div>

  <div class="row">
    <div class="large-6 small-12 columns large-centered">
      <div id="outputbox3">
        hello

      </div>
    </div>
  </div>

  <div class="row">
    <div class="large-6 columns" id="mypie3">

    </div>
  </div>
</section> -->


<!-- examples below -->
<!-- <div class="row">
<div class="large-6 columns">
<br /><br /><br /><br />
  <canvas id="canvas" width="200" height="200"></canvas>
  <table id="mydata">
    <tr>       <th>Lang</th><th>Value</th> </tr>
    <tr><td>JavaScript</td>  <td>100</td>  </tr>
    <tr><td>       CSS</td>  <td>200</td>  </tr>
    <tr><td>      HTML</td>  <td>300</td>  </tr>
    <tr><td>       PHP</td>  <td> 50</td>  </tr>
    <tr><td>     MySQL</td>  <td> 30</td>  </tr>
    <tr><td>    Apache</td>  <td> 10</td>  </tr>
    <tr><td>     Linux</td>  <td> 30</td>  </tr>
  </table>
</div>
</div>
-->