config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => "registrations" }
  devise_scope :user do
    get '/trip_preview/join/:id', :as=> 'trip_preview_join', :to => 'registrations#new'
  end
  
  get 'info_map/index'

  root to: 'visitors#index'
 
  authenticated :user do
    root 'user#show', as: :authenticated_root
  end

  resources :users, except: :index
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :trip, except: [:index, :edit] do
  	resources :trip_route, only: [:show]
    resources :comments, only: [:create]
    resources :itineraries, only:[:show]
  end
  
  resources :trip_preview, only: [:show]
  match '/trip_route/update', to: 'trip_route#update', via: [:post], constraints: { format: 'json' }
  match '/trip_route/stop/delete', to: 'trip_route#edit', via: [:post], constraints: { format: 'json' }
  match '/trip/:id', to: 'trip#update', via: [:patch], constraints: { format: 'json' }
  resources :comments
  resources :info_map, only: [:index]

  resource :budgets
  post '/budgets/compute' => 'budgets#compute'

end
 

app/models/trip.rb
class Trip < ActiveRecord::Base

	has_many :trip_memberships
	has_many :users, through: :trip_memberships
	has_one :trip_route
	belongs_to :itinerary
  has_many :comments

end

app/controllers/trip_controller.rb
class TripController < ApplicationController

  def show
  	@trip = Trip.find params[:id]
    # show last 10 most recent comments in the trip
    @comments = Comment.where(trip: @trip)
  	@route = @trip.trip_route.id
  end

  def new 
 	  @trip = Trip.new
	end

	def create
    prng = Random.new
		@trip = Trip.new(
      name: params[:trip]["name"],
      trip_code: prng.rand(100000...1000000)
    )
		if @trip.save
  		TripMembership.create(user_id: current_user.id, trip_id: @trip.id)
  		TripRoute.create(trip_id: @trip.id)
  		redirect_to trip_path(@trip.id)
		else
			flash[:failure] = "Please enter a name!"
		end
	end

  def update
    respond_to do |format|
      format.json {
        @trip = Trip.find params[:id]
        @trip.itinerary_id = params[:trip_id]
        if @trip.save
          data = {}
          data["redirect"] = "/trip/#{@trip.id}"
          render json: data
        end
      }
    end
  end
end

app/views/trip/new.html.erb
<div class="new-trip-wrapper">
  <h2 class="trip-name">What is the name of your trip?</h2>

  <%= form_for @trip, url: {action: "create"} do |f| %>
    <div class="form-group">
      <%= f.text_field :name, :autofocus => true, class: 'form-control', placeholder: 'enter trip name' %>
    </div>
  	<%= f.submit 'Get Started!', :class => 'button new' %>
  <% end %>
  <div class="content">
    <div class="grid">
      <div class="new-trip-img-1">
        <figure class="effect-julia">
          <%= image_tag("hiker-1149877_960_720.jpg", :alt => "rss feed") %>
          <figcaption>
            <h2 class="img-caption">World of <span>Wanderlust</span></h2>
            <div>
              <p class="img-caption">"We travel some of us forever."</p>
              <p class="img-caption">"We travel for fulfillment."</p>
              <p class="img-caption">"Beauty, Charm and Adventure."</p>
            </div>
            <a href="#">View more</a>
          </figcaption>
        </figure>
      </div>
      <div class="new-trip-img-2">
      <figure class="effect-julia">
        <%= image_tag("hiker-918704_960_720.jpg", :alt => "travelbug") %>
        <figcaption>
          <h2 class="img-caption">Travel Bug <span>Bites</span></h2>
          <div>
            <p class="img-caption">"Travel to take a journey."</p>
            <p class="img-caption">"Travel makes one modest."</p>
            <p class="img-caption">"The world is a book"</p>
          </div>
          <a href="#">View more</a>
        </figcaption>
      </figure>
    </div>
    </div>
</div>

app/views/trip/show.html.erb
<div class="trip-banner-container">
		<h1 class="trip-banner-header"><%= @trip.name.upcase %></h1>
</div>
	<div class="row">
		<div class="large-4 columns">
			<%= link_to image_tag('route-map.jpg', class: "route-link"), trip_trip_route_path(@trip.id, @route) %>
			<a href="https://www.facebook.com/sharer/sharer.php?u=http://backpackers.heroku.com/trip_preview/<%=@trip.trip_code %>&p[title]=Backpackers&p[summary]='Join me for my next amazing adventure! Click here to see what I have planned so far!'" title="Share on Facebook" target="_blank" class="btn btn-facebook"><%= image_tag('facebook.png', class: "facebook-share-link")%></a>
		</div>
		<div class="large-4 columns">
			<% if @trip.itinerary_id %>
				<h2>Saved Itinerary</h2>
				<ol>
					<% @trip.itinerary.cities.each do |stop| %>
					<li> <%= stop %> </li>
				<% end %>
			</ol>
			<% end %>
		</div>
		<div class="large-4 columns trip-chat-box">
			<%= render :partial => "shared/comments", :locals => {:comments => @comments} %>
		</div>
	</div>
	<div class = "row inspiration-header">
		<div class = "large-12 columns">
			<h2>Need Some Inspiration?</h2>
			<h4>Have a look at some of our hand selected sample itineraries.</h4>
		</div>
	</div>
<div class="row inspiration-countries">

  <div class="small-12 large-2 large-offset-1 columns">
    <%= link_to image_tag('europe.png'), trip_itinerary_path(@trip.id, "Europe") %>
  </div>
  <div class="small-12 large-2 columns">
    <%= link_to image_tag('asia.png'), trip_itinerary_path(@trip.id, "Asia") %>
  </div>
  <div class="small-12 large-2 columns">
    <%= link_to image_tag('south-central-america.png'), trip_itinerary_path(@trip.id,"Central%2FSouth America") %>
  </div>
  <div class="small-12 large-2 columns">
    <%= link_to image_tag('north-america.png'), trip_itinerary_path(@trip.id,"North America") %>
  </div>
  <div class="small-12 large-2 columns end">
    <%= link_to image_tag('australia-nz.png'), trip_itinerary_path(@trip.id,"Australia%2FNew Zealand") %>
  </div>
</div>